# Site settings
title: Studio Madsadcat
description: An emerging indie game studio based in Sydney, Australia

# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
email: studiomadsadcat@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://studiomadsadcat.com"
twitter_username: studiomadsadcat
github_username:  in-c0


# User settings
username: Studio Madsadcat
user_description: Welcome to Studio Madsadcat, a small game studio from Sydney started by a student with a love for creativity and gaming. We're currently working on our first project, aiming to turn everyday routines into something a little more fun. Thanks for stopping by and watching us grow!
user_title: Indie Game Studio
email: studiomadsadcat@gmail.com
twitter_username: studiomadsadcat
github_username:  in_c0
gplus_username:  studiomadsadcat

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
